[package]
name = "writing_helper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = "1.0.145"
serde_derive = "1.0.145"
serde_json = "1.0"
toml = "0.5.9"
